### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by LienReyserhove**
I updated the README.
Most important changes: see section ## Installation.
The rest is adapted from the alien fishes repository.

### CODE REVIEW

**Comment by peterdesmet** [comment]
Some comments (from phone)

- Don’t use dots for names and after year in citations (see citation format in other repos)
- Use backticks to refer to file names, not douvle quotes
- Repo structure heading appears twice
- Rmd should be rendered to docs: update repo structure and installation. See fishes (I guess) for inspiration

😊

**Comment by LienReyserhove** [comment]
Point 1-3: done

Point 4: In the fishes repo, we refer to the README of alien plants for the installation part. We haven't written an installation guide yet for .Rmd files. This was a first attempt. At this point, there's no docs folder present yet. I'm still not very familiar with this whole rendering process of .Rmd files to these nice documents, so maybe you should enlighten me :smile:

**Comment by peterdesmet** [comment]
I've just added the site to this branch. To be done:

- [x] Update installation steps
- [x] Update repo structure, see https://github.com/trias-project/alien-fishes-checklist/blob/master/README.md#repo-structure
- [x] Avoid too many links in README and use absolute links
- [x] Don't use `,` in references

**Comment by LienReyserhove** [comment]
Done.

With respect to the installation guide, I removed `run or adapt the code`.  I think it is sufficient to know how to run the code. To adapt the code, you really need more GithHub skills then those listed in the installation guide. Maybe we could add a "report an issue" section, to indicate that comments are always welcome.

**Review by peterdesmet — APPROVED** [review]
Added some further update to installation.

**Pull request merged**
