### PR TITLE
Checklist mapping

### PR DESCRIPTION
**Pull request by LienReyserhove**
This PR contains the first mapping of uredinales-belgium to DwC Archive.

This is short overview of all integrated terms and some extra information:

## pre-processing
The following steps were performed **before** further mapping:
- Generate taxonID
- Add full bibliographic citation (we need this in all generated .csv files)
- extract all one-to-one interactions between host plant and rust fungus

## taxon core

- We integrated both rust fungi and host plant information in the taxon core, each having its own taxonID. 
Not all DwC terms were mapped for the host plants.
- Please check whether the phylum + order information for the rust fungi is correct. 
- We parsed `scientificName` into `genus`, `specificEpithet`, `infraspecificEpithet`, `taxonRank`, `scientificNameAuthorship` using the parse function from rgif.

- [x] language
- [x] license
- [x] rightsHolder: "Botanic Garden Meise"
- [x] bibliographicCitation: full reference for rust fungi, simplified for host plants
- [x] institutionID "http://biocol.org/urn:lsid:biocol.org:col:15605"
- [x] datasetID
- [x] datasetName 
- [x] taxonID
- [x] scientificName
- [x] kingdom
- [x] phylum: Basidiomycota
- [x] order: Uredinales
- [x] family
- [x] genus
- [x] specificEpithet
- [x] infraspecificEpithet
- [x] scientificNameAuthorship
- [x] taxonRank
- [x] nomenclaturalCode: ICBN for both host and parasite species? The code os now called The International Code of Nomenclature for algae, fungi, and plants (ICN)

## distribution extension

- EventDate was removed from the raw data. We start from the raw information contained in `from` and `to` in the raw data file. Some extensive cleaning was needed.  

- [x] taxonID
- [x] locationID
- [x] locality (here under `country`)
- [x] countryCode
- [x] occurrenceStatus
- [x] establishmentMeans
- [x] eventDate
- [x] source (= bibliographicCitation)

## resource relationship extension

- Not sure if I used the correct terms, could you please check this? (I know we already discussed this, but I keep being confused on which ones to use, sorry for that)

- [x] resourceID (=taxonID of the host plant)
- [x] relatedResourceID (= taxonID of the rust fungus)
- [x] relationshipOfResource (= "parasite of")
- [x] relationshipAccordingTo (= bibliographicCitation)

### CODE REVIEW

**Review by qgroom — APPROVED** [review]
I've made a few minor changes, but otherwise it looks good.

**Comment by peterdesmet** [comment]
## Taxon

1. **Question: Is it possible to indicate the bibliographicCitation page for the host plants?**

We could provide a full bibliographicCitation for all plants species, thus including the volumne and page number for all plants species. However, I think it's "a lot of work" (a relative thing of course) for little gain. Some host plants recur in the checklist, in different volumes (e.g. `Allium ursinum` is found in both volume 2 and 3). This would imply linking the volume and page numbers to the host plant. We could do that, but the focus here is on the rust fungi, not really on the host plants.

2. **datasetName: would opt for `Catalogue of the Rust Fungi of Belgium` as that is closer to original publication title (i.e. not "checklist"). Personally I would not use "**The** Catalogue ..." and thus update README title.**

 `Catalogue of the Rust Fungi of Belgium`  --> OK, although @qgroom says this is not really grammatically correct. But we can keep it that way if you prefer.

3.  **Add taxonRank `genus` to host plant genera**

Sure. I do wonder why the parse function of rgbif doesn't recognize them as genus. Doesn't seem logic to me. 

 4. **Some scientificNameAuthorship are not populated by name parser, but that's OK.**

5. **Should we populate nomenclaturalCode with `ICN` (International Code of Nomenclature for algae, fungi, and plants) @qgroom? Also applies to other plant/fungi datasets.**

We could do that, Quentin has contacted the GBIF helpdesk for this issue. To be continued.

6.**bibliographicCitation, source. @groom, what citation style do you want to use?**

We will use the TrIAS citation style, without the dots and comma's. I will adapt this.

## Distribution

1. **For records with a single date (either start or end), it gets lost in `eventDate` if that was the start or end date. I'd maybe argue to always have a slash, e.g. `1902-07-16/` or `/1939`? @qgroom?**

We (me and @qgroom) are not very fond of the idea of integrating the slashes. It gives you the impression that the species is present from that point in time up to now. One date (start or end) implies that it has been observed a single time and that we only know it was present at that specific time and not further. We suggest to duplicate the single dates e.g. `1939/1939`. This clearly indicates that this species was observed one single time.

## ResourceRelationship

1. **Add a taxonID: I believe this is required by the IPT, but I could be wrong. Not sure yet which one to add (fungi or plant)...**

Not sure if I completely understand this. I could integrate a taxonID, but that would be identical to resourceID (i.e. the taxonID of the host plants). So than you just duplicate the information

2. **Use `parasite of` (no underscore)**

OK

## Source data

1. **So `Puccinia conglomerata` is absent? Why was it included in the checklist then?**

Same thing as for the alien plants checklist. It was included in the checklist because we are sure it is absent, opposing to other checklists suggesting the species is present 

2. **Lowercase subspecies `Prunus domestica subsp. Italica` and check if infraspecificEpithet gets populated; Lowercase subspecies `Pyrus communis subsp. Pyraster` and check if infraspecificEpithet gets populated**

OK

3. **Give last column (with establishmentMeans) a header name?**

We could name it `establishmentMeans` or means_of_establishment**

4. Are there plans to populate that last column further? For many taxa it is now unclear if they are native or introduced. @qgroom?

We prefer not to do this. This would mean interpreting the absent values, which could result in information that is not 100% correct. Better to leave it empty...

**Comment by peterdesmet** [comment]
I think it is more logical to define "host plant" relationships than "parasite" relationships (@qgroom, see #8, please respond there) but let's not have that stop this PR.

**Review by peterdesmet — CHANGES_REQUESTED** [review]
See https://github.com/trias-project/uredinales-belgium-checklist/pull/6#issuecomment-379056292

**Comment by LienReyserhove** [comment]
I responded to your questions / issues in https://github.com/trias-project/uredinales-belgium-checklist/pull/6#issuecomment-379056292. 

I make a new todo list here:

- [x] adapt datasetName 
- [x] add taxonRank `genus` to the host plant information
- [x] adapt bibliographicCitation to TrIAS house style
- [x] update eventDate to `1939/1939` style
- [x] lowercase subspecies in source data and check if GBIF finds a subspecies match
- [x] rename column in raw data (establishmentMeans)
- [x] use `parasite of`
- [x] add header `establishment_means` (or similar) to source data
- [x] update title in README
- [x] for plants, use bibliographicCitation: `Vanderweyen A & Fraiture A (2009 & 2012) Catalogue des Uredinales de Belgique. Lejeunia, Revue de Botanique.` (with `&` for year and including journal)

And a maybe todo list (depending on the outcome of the discussions):

- [x] populate `nomenclaturalCode` with `ICN`
- [x] add taxonID in resource relationship: would add it for now (= `resourceID` = host plant), to avoid being stuck in IPT.

**Comment by peterdesmet** [comment]
Thanks for the answers: agree with all. I have added some items to your new to do list. Will review again when you ask.

**Comment by qgroom** [comment]
According to GBIF it is OK to use ICN as the official abbreviation for the 	
International Code of Nomenclature for algae, fungi and plants http://rs.gbif.org/vocabulary/gbif/nomenclatural_code.xml

**Comment by LienReyserhove** [comment]
Then, do we use ICN for the manual of alien plants as well?

**Comment by LienReyserhove** [comment]
@peterdesmet : I integrated the requested changes. Now ready for review!

**Review by peterdesmet — APPROVED** [review]

**Comment by peterdesmet** [comment]
Made some minor corrections, can be merged and then #13 can be tackled.

**Pull request merged**
